export type QuestionType = "single" | "multiple";
export type Difficulty = "easy" | "medium" | "hard";

export interface Question {
  id: number;
  lecture: number;
  text: string;
  type: QuestionType;
  options: string[];
  correctAnswers: number[];
  difficulty: Difficulty;
  points: number;
}

// Distribution: 30 easy×3 + 50 medium×5 + 20 hard×8 = 90+250+160 = 500 pts
export const questions: Question[] = [
  // ─── LECTURE 1: Fundamentals of Testing (14 questions) ───────────────────
  {
    id: 1,
    lecture: 1,
    text: "What is the primary goal of software testing?",
    type: "single",
    options: [
      "To prove that the software is correct",
      "To find defects and provide information about quality",
      "To make the software defect-free",
      "To replace code reviews",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 2,
    lecture: 1,
    text: "Which of the following best describes a 'defect' in software testing?",
    type: "single",
    options: [
      "A mistake made by a developer while typing code",
      "An imperfection in a work product that may cause it to fail to meet requirements",
      "A deviation of the component or system from its expected behavior",
      "A failure observed during test execution",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 3,
    lecture: 1,
    text: "According to ISTQB, what is the difference between an error, defect, and failure?",
    type: "single",
    options: [
      "They all mean the same thing",
      "Error is made by human, defect is in the product, failure is observable deviation",
      "Failure is made by human, error is in the product, defect is observable deviation",
      "Defect is made by human, error is in the product, failure is in the test",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 4,
    lecture: 1,
    text: "Which testing principle states that testing shows the presence of defects but cannot prove their absence?",
    type: "single",
    options: [
      "Exhaustive testing is impossible",
      "Testing is context dependent",
      "Testing shows presence of defects",
      "Early testing saves time and money",
    ],
    correctAnswers: [2],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 5,
    lecture: 1,
    text: "Which of the following are valid objectives of testing? (Select all that apply)",
    type: "multiple",
    options: [
      "Finding defects",
      "Proving the software has no bugs",
      "Gaining confidence in quality",
      "Preventing defects",
      "Providing information for decision-making",
    ],
    correctAnswers: [0, 2, 3, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 6,
    lecture: 1,
    text: "The Pesticide Paradox principle suggests that:",
    type: "single",
    options: [
      "Testing is most effective when done at the end",
      "If the same tests are repeated, they will find fewer new defects over time",
      "Defects cluster in a small number of modules",
      "Exhaustive testing is impossible",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 7,
    lecture: 1,
    text: "Which testing principle states that defects tend to cluster in a small number of modules?",
    type: "single",
    options: [
      "Exhaustive testing is impossible",
      "Early testing saves time and money",
      "Defect clustering",
      "Pesticide paradox",
    ],
    correctAnswers: [2],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 8,
    lecture: 1,
    text: "What is 'verification' in software testing?",
    type: "single",
    options: [
      "Checking whether the system meets the end user's actual needs",
      "Checking whether the system conforms to specified requirements",
      "Running the software to find defects",
      "Reviewing the test plan",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 9,
    lecture: 1,
    text: "What is 'validation' in software testing?",
    type: "single",
    options: [
      "Checking whether the system conforms to specifications",
      "Checking whether the system meets the end user's actual needs",
      "Executing test cases",
      "Logging defects in a defect tracking system",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 10,
    lecture: 1,
    text: "Which of the following is a benefit of early testing?",
    type: "single",
    options: [
      "It guarantees the software is defect-free",
      "It reduces the cost of fixing defects found later",
      "It eliminates the need for regression testing",
      "It allows skipping unit testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 11,
    lecture: 1,
    text: "The 'absence-of-errors fallacy' principle means:",
    type: "single",
    options: [
      "A system with no errors is always usable",
      "Finding and fixing defects does not help if the system does not fulfill user needs",
      "Errors cannot be absent from a system",
      "All errors must be found before release",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 12,
    lecture: 1,
    text: "Which activities are part of the fundamental test process? (Select all that apply)",
    type: "multiple",
    options: [
      "Test planning",
      "Test analysis and design",
      "Test implementation and execution",
      "Test closure",
      "Code writing",
    ],
    correctAnswers: [0, 1, 2, 3],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 13,
    lecture: 1,
    text: "In testing psychology, which behavior is most constructive for a tester?",
    type: "single",
    options: [
      "Blaming developers for all defects",
      "Communicating defects constructively and objectively",
      "Avoiding communication with developers",
      "Reporting only critical defects",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 14,
    lecture: 1,
    text: "Which statement about independent testing is TRUE?",
    type: "single",
    options: [
      "Developers should never test their own code",
      "Independent testers are always more effective than developer testing",
      "Independence in testing can range from no independence to fully independent teams",
      "Only external teams provide true independent testing",
    ],
    correctAnswers: [2],
    difficulty: "hard",
    points: 8,
  },

  // ─── LECTURE 2: Testing Throughout SDLC (14 questions) ───────────────────
  {
    id: 15,
    lecture: 2,
    text: "In a V-model, system testing corresponds to which development activity?",
    type: "single",
    options: [
      "Unit design",
      "System design",
      "Requirements specification",
      "Architecture design",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 16,
    lecture: 2,
    text: "Which test level focuses on the interactions between integrated components?",
    type: "single",
    options: [
      "Unit testing",
      "Integration testing",
      "System testing",
      "Acceptance testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 17,
    lecture: 2,
    text: "What is the main objective of User Acceptance Testing (UAT)?",
    type: "single",
    options: [
      "To find defects in individual components",
      "To verify that the system meets business requirements and is ready for deployment",
      "To test the system's performance under load",
      "To verify integration between components",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 18,
    lecture: 2,
    text: "Which test types are classified as functional testing? (Select all that apply)",
    type: "multiple",
    options: [
      "Security testing",
      "Usability testing",
      "Smoke testing",
      "Performance testing",
      "Regression testing",
    ],
    correctAnswers: [0, 2, 4],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 19,
    lecture: 2,
    text: "In Agile development, which testing activity best fits the 'shift-left' approach?",
    type: "single",
    options: [
      "Performing acceptance testing after every sprint",
      "Testing earlier in the development lifecycle, including during requirements analysis",
      "Leaving all testing to the end of the project",
      "Only performing regression testing",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 20,
    lecture: 2,
    text: "What is regression testing?",
    type: "single",
    options: [
      "Testing a new feature for the first time",
      "Re-testing previously tested code after changes to ensure no new defects were introduced",
      "Testing the system under extreme conditions",
      "Testing the usability of the interface",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 21,
    lecture: 2,
    text: "Which SDLC model works best when requirements are well-understood and unlikely to change?",
    type: "single",
    options: [
      "Scrum",
      "Kanban",
      "Waterfall",
      "Extreme Programming (XP)",
    ],
    correctAnswers: [2],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 22,
    lecture: 2,
    text: "What is the purpose of a smoke test (sanity check)?",
    type: "single",
    options: [
      "To test all functionalities in depth",
      "To quickly verify that the most critical functions work after a build",
      "To test the system's security",
      "To find all defects before release",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 23,
    lecture: 2,
    text: "Which of the following statements about testing in Agile is CORRECT?",
    type: "single",
    options: [
      "Testing only happens at the end of the sprint",
      "Testers are not needed in Agile teams",
      "Testing is a continuous activity throughout the iteration",
      "Automated testing is optional in Agile",
    ],
    correctAnswers: [2],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 24,
    lecture: 2,
    text: "What is the main difference between white-box and black-box testing?",
    type: "single",
    options: [
      "White-box testing uses automated tools, black-box does not",
      "White-box testing is based on internal structure; black-box on external behavior",
      "Black-box testing is performed by developers; white-box by testers",
      "White-box testing is only done at unit level",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 25,
    lecture: 2,
    text: "Maintenance testing is triggered by which of the following? (Select all that apply)",
    type: "multiple",
    options: [
      "Modification of software",
      "Migration of software to a new platform",
      "Retirement of software",
      "Initial software development",
      "Code reviews",
    ],
    correctAnswers: [0, 1, 2],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 26,
    lecture: 2,
    text: "In the V-model, at which stage are test conditions derived?",
    type: "single",
    options: [
      "During code implementation",
      "During the corresponding development level (e.g., requirements for acceptance tests)",
      "Only after all development is complete",
      "During regression testing",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 27,
    lecture: 2,
    text: "Non-functional testing includes which of the following? (Select all that apply)",
    type: "multiple",
    options: [
      "Performance testing",
      "Security testing",
      "Usability testing",
      "Functional testing",
      "Reliability testing",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 28,
    lecture: 2,
    text: "Which term describes the degree to which a component or system can be tested?",
    type: "single",
    options: [
      "Reliability",
      "Testability",
      "Maintainability",
      "Portability",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },

  // ─── LECTURE 3: Static Testing (14 questions) ────────────────────────────
  {
    id: 29,
    lecture: 3,
    text: "Static testing differs from dynamic testing in that:",
    type: "single",
    options: [
      "Static testing requires running the software",
      "Static testing examines work products without executing code",
      "Static testing only applies to test documentation",
      "Static testing is performed only by developers",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 30,
    lecture: 3,
    text: "Which of the following are work products that can be examined with static testing? (Select all that apply)",
    type: "multiple",
    options: [
      "Requirements specifications",
      "Source code",
      "Test plans",
      "User manuals",
      "Log files from test execution",
    ],
    correctAnswers: [0, 1, 2, 3],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 31,
    lecture: 3,
    text: "What is the role of a 'moderator' in a formal review?",
    type: "single",
    options: [
      "To write the document being reviewed",
      "To facilitate the review meeting and ensure the process is followed",
      "To find all defects in the document",
      "To approve the document for release",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 32,
    lecture: 3,
    text: "Which review type is the most formal and structured?",
    type: "single",
    options: [
      "Walkthrough",
      "Informal review",
      "Inspection",
      "Technical review",
    ],
    correctAnswers: [2],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 33,
    lecture: 3,
    text: "In a walkthrough, who leads the review session?",
    type: "single",
    options: [
      "The moderator",
      "The author of the work product",
      "The manager",
      "An independent tester",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 34,
    lecture: 3,
    text: "Which of the following are typical defects found by static analysis tools? (Select all that apply)",
    type: "multiple",
    options: [
      "Undefined variables",
      "Security vulnerabilities",
      "Coding standard violations",
      "Performance bottlenecks at runtime",
      "Dead code",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 35,
    lecture: 3,
    text: "What is a checklist-based review technique?",
    type: "single",
    options: [
      "A technique where reviewers use a predefined list of questions to guide the review",
      "A technique where reviewers check code against test cases",
      "A review performed without any structure",
      "A technique only used in security reviews",
    ],
    correctAnswers: [0],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 36,
    lecture: 3,
    text: "Which review type is characterized by peer review where participants check the work from different perspectives?",
    type: "single",
    options: [
      "Informal review",
      "Walkthrough",
      "Technical review",
      "Inspection",
    ],
    correctAnswers: [2],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 37,
    lecture: 3,
    text: "What is the main benefit of static testing over dynamic testing?",
    type: "single",
    options: [
      "It finds all runtime defects",
      "Defects can be found earlier and more cheaply before code is executed",
      "It requires no human effort",
      "It replaces the need for dynamic testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 38,
    lecture: 3,
    text: "In formal reviews, what is the 'scribe' responsible for?",
    type: "single",
    options: [
      "Leading the review meeting",
      "Recording defects and issues found during the review",
      "Deciding which defects are critical",
      "Distributing review invitations",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 39,
    lecture: 3,
    text: "Which of the following describes a 'perspective-based reading' technique in reviews?",
    type: "single",
    options: [
      "Reading the document from beginning to end",
      "Each reviewer reads the document from the viewpoint of a different stakeholder",
      "Having the author read the document aloud",
      "Comparing the document to a checklist",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 40,
    lecture: 3,
    text: "Which factors contribute to a successful review? (Select all that apply)",
    type: "multiple",
    options: [
      "Clear objectives",
      "Appropriate review type for the context",
      "Management support",
      "Blaming authors for defects found",
      "Sufficient preparation time",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 41,
    lecture: 3,
    text: "Static analysis is performed by:",
    type: "single",
    options: [
      "Executing the program with test inputs",
      "Tools that examine source code without executing it",
      "Manually reading documentation",
      "Running performance tests",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 42,
    lecture: 3,
    text: "Which metric is commonly used in formal inspections to measure review effectiveness?",
    type: "single",
    options: [
      "Number of test cases executed",
      "Defect density (defects per page or per KLOC)",
      "Lines of code written",
      "Number of test automation scripts",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },

  // ─── LECTURE 4: Test Analysis and Design (15 questions) ──────────────────
  {
    id: 43,
    lecture: 4,
    text: "Equivalence Partitioning divides input data into partitions. Which statement is CORRECT?",
    type: "single",
    options: [
      "All values in a partition are expected to be processed differently",
      "All values in a partition are expected to be processed in the same way",
      "Partitions are only used for numerical inputs",
      "You must test every value within a partition",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 44,
    lecture: 4,
    text: "For a field that accepts values 1-100, which values represent Boundary Value Analysis test cases?",
    type: "multiple",
    options: [
      "0",
      "1",
      "50",
      "100",
      "101",
    ],
    correctAnswers: [0, 1, 3, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 45,
    lecture: 4,
    text: "A decision table is most useful when:",
    type: "single",
    options: [
      "Testing sequential workflows",
      "Testing complex business logic with multiple conditions and actions",
      "Testing performance requirements",
      "Testing navigation between screens",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 46,
    lecture: 4,
    text: "State transition testing is based on:",
    type: "single",
    options: [
      "The flow of data through the system",
      "The system's behavior as it transitions between states in response to events",
      "The performance of the system under load",
      "The logical conditions in the code",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 47,
    lecture: 4,
    text: "Which coverage criterion requires that every statement in the code is executed at least once?",
    type: "single",
    options: [
      "Branch coverage",
      "Statement coverage",
      "Condition coverage",
      "Path coverage",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 48,
    lecture: 4,
    text: "Which of the following are experience-based test techniques? (Select all that apply)",
    type: "multiple",
    options: [
      "Error guessing",
      "Exploratory testing",
      "Equivalence partitioning",
      "Checklist-based testing",
      "Decision table testing",
    ],
    correctAnswers: [0, 1, 3],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 49,
    lecture: 4,
    text: "Branch coverage (also called decision coverage) requires:",
    type: "single",
    options: [
      "Every line of code to be executed",
      "Every branch from each decision point to be executed at least once",
      "Every possible path through the code to be tested",
      "Every condition to be true and false independently",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 50,
    lecture: 4,
    text: "For an age field accepting values 0-120, using Equivalence Partitioning, which partitions are correct?",
    type: "multiple",
    options: [
      "Invalid partition: values < 0",
      "Valid partition: 0-120",
      "Invalid partition: values > 120",
      "Valid partition: 0-60 only",
      "Invalid partition: non-numeric values",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 51,
    lecture: 4,
    text: "Use case testing derives test cases from:",
    type: "single",
    options: [
      "The internal structure of the code",
      "Scenarios describing interactions between actors and the system",
      "Performance requirements",
      "Security vulnerabilities",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 52,
    lecture: 4,
    text: "Which statement about 100% statement coverage is TRUE?",
    type: "single",
    options: [
      "It guarantees all defects are found",
      "It means every branch has been tested",
      "It does not guarantee 100% branch coverage",
      "It is impossible to achieve in practice",
    ],
    correctAnswers: [2],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 53,
    lecture: 4,
    text: "Exploratory testing is BEST described as:",
    type: "single",
    options: [
      "Testing without any preparation or documentation",
      "Simultaneous test design, execution, and learning to investigate the system",
      "Testing only the happy path scenarios",
      "Testing performed exclusively by experienced developers",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 54,
    lecture: 4,
    text: "A test condition is:",
    type: "single",
    options: [
      "The same as a test case",
      "An aspect of the test object that can be verified by one or more test cases",
      "The expected result of a test",
      "A requirement that must be tested",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 55,
    lecture: 4,
    text: "In a decision table with 3 binary conditions, how many unique rule combinations are possible?",
    type: "single",
    options: [
      "3",
      "6",
      "8",
      "9",
    ],
    correctAnswers: [2],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 56,
    lecture: 4,
    text: "Which technique tests all possible transitions in a state machine model?",
    type: "single",
    options: [
      "All-states coverage",
      "All-transitions coverage",
      "All-paths coverage",
      "Decision table testing",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 57,
    lecture: 4,
    text: "Error guessing is typically based on which of the following? (Select all that apply)",
    type: "multiple",
    options: [
      "Tester's experience",
      "Knowledge of defect taxonomies",
      "Formal mathematical models",
      "Knowledge of how the system is likely to fail",
      "Random selection of test inputs",
    ],
    correctAnswers: [0, 1, 3],
    difficulty: "medium",
    points: 5,
  },

  // ─── LECTURE 5: Managing Test Activities (14 questions) ──────────────────
  {
    id: 58,
    lecture: 5,
    text: "What is the main purpose of a Test Plan?",
    type: "single",
    options: [
      "To document all defects found during testing",
      "To describe the scope, approach, resources, and schedule of testing activities",
      "To list all test cases",
      "To report test results to stakeholders",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 59,
    lecture: 5,
    text: "Which of the following are test estimation techniques? (Select all that apply)",
    type: "multiple",
    options: [
      "Expert estimation",
      "Wideband Delphi",
      "Work breakdown structure (WBS)",
      "Pareto analysis",
      "Metrics-based estimation",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 60,
    lecture: 5,
    text: "Risk-based testing prioritizes tests based on:",
    type: "single",
    options: [
      "The number of test cases available",
      "The likelihood and impact of potential failures",
      "The time required to execute tests",
      "The preferences of the development team",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 61,
    lecture: 5,
    text: "What is a 'product risk' in software testing?",
    type: "single",
    options: [
      "A risk that affects the testing schedule",
      "A risk that the software may fail to meet quality requirements",
      "A risk related to the test team's skills",
      "A risk that the test environment will not be available",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 62,
    lecture: 5,
    text: "What is a 'project risk' in software testing?",
    type: "single",
    options: [
      "The risk that the software has defects",
      "Factors that may impact the success of the project itself (schedule, resources, etc.)",
      "The risk that users will reject the software",
      "The risk that test automation will fail",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 63,
    lecture: 5,
    text: "Which of the following are typical entry criteria for test execution? (Select all that apply)",
    type: "multiple",
    options: [
      "Test environment is ready",
      "Test data is available",
      "All defects are fixed",
      "Test cases are reviewed and approved",
      "Build is available for testing",
    ],
    correctAnswers: [0, 1, 3, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 64,
    lecture: 5,
    text: "A test summary report is typically created:",
    type: "single",
    options: [
      "Before testing begins",
      "During test execution only",
      "At the end of a testing phase to summarize activities and results",
      "Only when testing fails",
    ],
    correctAnswers: [2],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 65,
    lecture: 5,
    text: "Which document formally defines the test levels, types, approach, and resources for a specific test level?",
    type: "single",
    options: [
      "Test summary report",
      "Test strategy",
      "Test plan",
      "Test charter",
    ],
    correctAnswers: [2],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 66,
    lecture: 5,
    text: "Configuration management in testing ensures:",
    type: "single",
    options: [
      "Testers are properly scheduled",
      "The integrity and traceability of test items, test documentation, and related work products",
      "Test automation is properly coded",
      "The development environment is stable",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 67,
    lecture: 5,
    text: "What information should a good defect report contain? (Select all that apply)",
    type: "multiple",
    options: [
      "Steps to reproduce the defect",
      "Expected result",
      "Actual result",
      "Name of the developer who wrote the code",
      "Severity and priority",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 68,
    lecture: 5,
    text: "What is the difference between defect severity and defect priority?",
    type: "single",
    options: [
      "They mean the same thing",
      "Severity is the impact on functionality; priority is the urgency to fix it",
      "Priority is the impact on functionality; severity is the urgency to fix it",
      "Severity is set by developers; priority is set by testers",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 69,
    lecture: 5,
    text: "Test monitoring involves:",
    type: "single",
    options: [
      "Executing the test cases",
      "Gathering information about testing progress and comparing it against the test plan",
      "Writing new test cases",
      "Fixing defects found during testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 70,
    lecture: 5,
    text: "Exit criteria (also called 'definition of done' in Agile) serve to:",
    type: "single",
    options: [
      "Define when testing activities may be suspended or concluded",
      "Define when testing activities should begin",
      "List all test cases to be executed",
      "Identify who performs testing",
    ],
    correctAnswers: [0],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 71,
    lecture: 5,
    text: "Which of the following are valid test metrics? (Select all that apply)",
    type: "multiple",
    options: [
      "Test case pass/fail rate",
      "Defect density",
      "Test coverage",
      "Lines of code written",
      "Defect detection percentage",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "hard",
    points: 8,
  },

  // ─── LECTURE 6: Test Tools (15 questions) ────────────────────────────────
  {
    id: 72,
    lecture: 6,
    text: "Which of the following are categories of test tools? (Select all that apply)",
    type: "multiple",
    options: [
      "Test management tools",
      "Test automation tools",
      "Performance testing tools",
      "Code compilation tools",
      "Defect tracking tools",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 73,
    lecture: 6,
    text: "What is the main purpose of a test management tool?",
    type: "single",
    options: [
      "To automatically execute test scripts",
      "To support planning, monitoring, and control of testing activities",
      "To measure code coverage",
      "To perform performance testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 74,
    lecture: 6,
    text: "Which of the following statements about test automation is TRUE?",
    type: "single",
    options: [
      "Test automation eliminates the need for manual testing",
      "Test automation provides immediate ROI from day one",
      "Test automation is most effective for repetitive regression tests",
      "Test automation always finds more defects than manual testing",
    ],
    correctAnswers: [2],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 75,
    lecture: 6,
    text: "What is a 'test harness'?",
    type: "single",
    options: [
      "A hardware device used for testing",
      "A collection of software and test data used to test a program unit",
      "A checklist used in code reviews",
      "A performance testing framework",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 76,
    lecture: 6,
    text: "Keyword-driven test automation is characterized by:",
    type: "single",
    options: [
      "Writing test scripts in low-level programming languages",
      "Using keywords that represent actions, allowing non-programmers to create tests",
      "Capturing and replaying user interactions",
      "Testing with random input data",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 77,
    lecture: 6,
    text: "Which tool type is used to measure how much of the source code is exercised by test suites?",
    type: "single",
    options: [
      "Performance testing tools",
      "Code coverage tools",
      "Test management tools",
      "Defect tracking tools",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 78,
    lecture: 6,
    text: "What are the main risks of test automation? (Select all that apply)",
    type: "multiple",
    options: [
      "High initial investment in time and resources",
      "Maintenance effort as the application changes",
      "Overconfidence in automated test results",
      "Finding fewer defects than manual testing",
      "Automated tests may not detect all defect types",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 79,
    lecture: 6,
    text: "A 'capture/playback' automation approach works by:",
    type: "single",
    options: [
      "Writing test scripts from scratch in a programming language",
      "Recording user interactions and replaying them as automated scripts",
      "Using keywords to represent test actions",
      "Generating tests automatically from requirements",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 80,
    lecture: 6,
    text: "Which of the following are performance testing tool capabilities? (Select all that apply)",
    type: "multiple",
    options: [
      "Simulating multiple concurrent users",
      "Measuring response time",
      "Monitoring system resource utilization",
      "Automatically fixing performance defects",
      "Generating performance reports",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 81,
    lecture: 6,
    text: "What is the 'Page Object Model' in test automation?",
    type: "single",
    options: [
      "A performance optimization pattern",
      "A design pattern that creates an abstraction layer for UI elements to improve maintainability",
      "A tool for managing test data",
      "A framework for API testing",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 82,
    lecture: 6,
    text: "Which factor is MOST important when selecting a test automation tool?",
    type: "single",
    options: [
      "The tool's popularity",
      "The tool's compatibility with the system under test and existing technologies",
      "The vendor's reputation",
      "The number of features the tool offers",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 83,
    lecture: 6,
    text: "Data-driven testing differs from keyword-driven testing in that:",
    type: "single",
    options: [
      "Data-driven testing uses different datasets to drive the same test logic",
      "Data-driven testing requires programming skills while keyword-driven does not",
      "Data-driven testing is only for performance testing",
      "Data-driven testing cannot be automated",
    ],
    correctAnswers: [0],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 84,
    lecture: 6,
    text: "What is Continuous Integration (CI) in the context of testing?",
    type: "single",
    options: [
      "Manually running all tests before each release",
      "Automatically building and testing code changes frequently to detect issues early",
      "A method for writing test cases",
      "A performance testing approach",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 85,
    lecture: 6,
    text: "Which of the following tools are typically used for API testing? (Select all that apply)",
    type: "multiple",
    options: [
      "Postman",
      "JMeter",
      "REST Assured",
      "Selenium",
      "SoapUI",
    ],
    correctAnswers: [0, 2, 4],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 86,
    lecture: 6,
    text: "The Test Automation Pyramid suggests that:",
    type: "single",
    options: [
      "Most tests should be UI-level automated tests",
      "You should have more unit tests than integration tests, and more integration tests than UI tests",
      "Manual testing should form the base of the pyramid",
      "All tests should be at the same level",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },

  // ─── LECTURE 7: Advanced Topics & Review (14 questions) ──────────────────
  {
    id: 87,
    lecture: 7,
    text: "Which ISTQB testing principle emphasizes that testing should be adapted to the context and risks of the project?",
    type: "single",
    options: [
      "Exhaustive testing is impossible",
      "Testing is context dependent",
      "Early testing saves time and money",
      "Defect clustering",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 88,
    lecture: 7,
    text: "Which of the following best describes 'test oracle'?",
    type: "single",
    options: [
      "A database used to store test data",
      "A mechanism or source to determine whether the actual result matches the expected result",
      "An automated test execution tool",
      "A senior tester who reviews test cases",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 89,
    lecture: 7,
    text: "What is 'test basis'?",
    type: "single",
    options: [
      "The test environment used for testing",
      "The body of knowledge used as a basis to derive test cases",
      "The minimum set of test cases needed",
      "The baseline version of software being tested",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 90,
    lecture: 7,
    text: "Which of the following are characteristics of good test cases? (Select all that apply)",
    type: "multiple",
    options: [
      "Each test case has a unique identifier",
      "Preconditions are clearly defined",
      "Expected results are specified before execution",
      "Test cases always pass",
      "Steps are clear and reproducible",
    ],
    correctAnswers: [0, 1, 2, 4],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 91,
    lecture: 7,
    text: "What is the purpose of a 'test stub'?",
    type: "single",
    options: [
      "A stub is used to replace a called component during integration testing",
      "A stub is used to replace a calling component during integration testing",
      "A stub is a type of test case",
      "A stub is documentation for a test module",
    ],
    correctAnswers: [0],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 92,
    lecture: 7,
    text: "What is a 'test driver'?",
    type: "single",
    options: [
      "A component that replaces a called module",
      "A component that calls the module under test, simulating the calling component",
      "A type of test automation framework",
      "A person who drives test execution",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 93,
    lecture: 7,
    text: "In top-down integration testing, what is used to replace lower-level components not yet developed?",
    type: "single",
    options: [
      "Drivers",
      "Stubs",
      "Mocks",
      "Proxies",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 94,
    lecture: 7,
    text: "Which of the following statements about test independence are TRUE? (Select all that apply)",
    type: "multiple",
    options: [
      "Some independence in testing can increase defect detection effectiveness",
      "Fully independent testing always produces the best results",
      "Developers can benefit from testing their own code",
      "Independence introduces an objective viewpoint",
      "Independence always prevents confirmation bias completely",
    ],
    correctAnswers: [0, 2, 3],
    difficulty: "hard",
    points: 8,
  },
  {
    id: 95,
    lecture: 7,
    text: "Which testing activity is performed to verify that previously fixed defects have not reappeared?",
    type: "single",
    options: [
      "Regression testing",
      "Confirmation testing (re-testing)",
      "Smoke testing",
      "Exploratory testing",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 96,
    lecture: 7,
    text: "The 80/20 rule (Pareto principle) in testing suggests that:",
    type: "single",
    options: [
      "80% of tests should be automated",
      "Approximately 80% of defects are found in 20% of modules",
      "Testing should take 80% of the project time",
      "20% of requirements cause 80% of test failures",
    ],
    correctAnswers: [1],
    difficulty: "easy",
    points: 3,
  },
  {
    id: 97,
    lecture: 7,
    text: "What is the key difference between re-testing and regression testing?",
    type: "single",
    options: [
      "They are the same thing",
      "Re-testing confirms a specific defect is fixed; regression testing checks that fixes did not introduce new defects",
      "Regression testing is performed first; re-testing follows",
      "Re-testing is automated; regression testing is manual",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 98,
    lecture: 7,
    text: "What does 'traceability' mean in the context of software testing?",
    type: "single",
    options: [
      "The ability to track the execution time of test cases",
      "The ability to link test cases to requirements, risks, and other test artifacts",
      "The ability to reproduce defects consistently",
      "The process of monitoring test progress",
    ],
    correctAnswers: [1],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 99,
    lecture: 7,
    text: "Which of the following are typical contents of a test completion report? (Select all that apply)",
    type: "multiple",
    options: [
      "Summary of testing activities",
      "Deviations from the test plan",
      "Outstanding defects and risks",
      "Lessons learned",
      "Detailed code review findings",
    ],
    correctAnswers: [0, 1, 2, 3],
    difficulty: "medium",
    points: 5,
  },
  {
    id: 100,
    lecture: 7,
    text: "Which of the following BEST describes the concept of 'quality assurance' vs 'quality control'?",
    type: "single",
    options: [
      "They are the same thing",
      "QA focuses on defect prevention through process improvement; QC focuses on defect detection in products",
      "QC focuses on process improvement; QA focuses on defect detection",
      "QA is performed by testers; QC is performed by developers",
    ],
    correctAnswers: [1],
    difficulty: "hard",
    points: 8,
  },
];

export const MAX_SCORE = questions.reduce((sum, q) => sum + q.points, 0); // 500

export function calculateScore(
  answers: Record<number, number[]>
): { score: number; correct: number } {
  let score = 0;
  let correct = 0;

  for (const question of questions) {
    const given = (answers[question.id] ?? []).slice().sort();
    const expected = question.correctAnswers.slice().sort();
    const isCorrect =
      given.length === expected.length &&
      given.every((v, i) => v === expected[i]);
    if (isCorrect) {
      score += question.points;
      correct++;
    }
  }

  return { score, correct };
}
